### ISSUE TITLE
Subscribe: Check for Name/Mail is not reliable

### ISSUE THREAD

**Issue by benleb** [hft-swp2-ws1516/website#52] opened 2016-01-18 09:55 UTC
Sorry but...

If i write a name/mail in the fields, everything works like it should...

if i choose a name/mail from my autofill-list (suggestion from your browser with previously used names/mails) it doesnt work.
for a non-technical user, this would seem like a serious bug which prevents registering for our newsletter... please fix!

**Comment by ghost** [comment] 2016-01-18 15:10
No need to say 'Sorry'. The problem you are referring to is one that I have also noticed and it seems that it is caused by the fact that both the 'Name' and the 'Mail' field are linked to the validation logic by using the 'KeyUp' event. In my opinion, this isn't necessarily optimal because of the fact that as long as a user has not finished typing, his input does not need to be checked - in case of the e-mail address, it will be invalid anyway until he is done. @22beer1bif: May I suggest you replace the 'KeyUp' event with the 'OnBlur' event? This would be sufficient for input typing as well as selecting values from the auto-fill list your browser provides. The user would still have to press TAB or leave the current input field to trigger the event so this approach is not perfect, but it would work better than the current one.

**Comment by KNiedziela** [comment] 2016-01-18 20:12
I have a small suggestion. Would it be better to use the "pattern" HTML attribute?(for the validation)

**Closed as completed** 2016-01-19 22:46 UTC
